services:
  front:
    image: wonecode/paprika-front-staging
    ports:
      - 3000:3000
    volumes:
      - ./src/:/wonecode/paprika-front-staging/src/
      - ./public/:/wonecode/paprika-front-staging/public/
    depends_on:
      back:
        condition: service_started
    command: npm start
  back:
    image: melissakintz/paprika-back-staging
    ports:
      - 4000:4000
    volumes:
      - ./src/:/paprika-back/src/
    restart: always
    links:
      - mysqldb
    depends_on:
      mysqldb:
        condition: service_healthy
  mysqldb:
    image: mysql
    healthcheck:
      test: 'exit 0'
    restart: always
    environment:
      MYSQL_DATABASE: paprika
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
