services:
  parika-back:
    image: paprika-back
    ports:
      - 4000:4000
    volumes:
      - ./src/:/paprika-back/src/
    links:
      - mysqldb
    depends_on:
      - mysqldb
  mysqldb:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: paprika
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
